version: "3.3"

services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - ./calibre/config:/config
      - ./calibre/plugins:/plugins
      - ./calibre/data:/Calibre_Library
      - ./calibre/uploads:/uploads
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped
    networks:
      - ebooks
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - ./calibre-web/config:/config
      - ./calibre/data:/books
    restart: unless-stopped
    depends_on:
      - calibre
    ports:
      - 8083:8083
    networks:
      - ebooks
  syncsource:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncsource
    environment:
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - ./syncthing/config-source:/config
      - ./calibre/data:/books
      - ./calibre/uploads:/uploads
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
  synctarget:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: synctarget
    environment:
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - ./syncthing/config-target:/config
      - $SYNC_FOLDER:/books
      - $UPLOAD_FOLDER:/uploads
    ports:
      - 8385:8384
      - 22001:22000/tcp
      - 22001:22000/udp
      - 21028:21027/udp
    restart: unless-stopped

networks:
  ebooks:
    driver: bridge
